language: java
jdk: 
  - openjdk8

branches: 
  only:
    - master

#Travis CI 서버 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-practice *
  - mkdir -p deploy
  - mv springboot-practice.zip deploy/

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: build-springboot-practice
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-unil-deployed: true

notification: 
  email:
    recipients:
      - rhdtl78@gmail.com