language: java
jdk: 
  - openjdk8

branches: 
  only:
    - master

#Travis CI 서버 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before_deploy
  - cp scripts/*.sh before_deploy/
  - cp appspec.yml before_deploy/
  - cp build/libs/*.jar before_deploy/
  - cd before_deploy && zip -r before_deploy *
  - cd ../ && mkdir -p deploy
  - mv before_deploy/before_deploy.zip deploy/springboot-practice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: build-springboot-practice
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-unil-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: build-springboot-practice
    key: springboot-practice.zip

    bundle_type: zip
    application: springboot-practice

    deployment_group: springboot-practice-group
    region: ap-northeast-2
    wait-unil-deployed: true

notification: 
  email:
    recipients:
      - rhdtl78@gmail.com